branches:
  only:
  - master
  - /^v[0-9]/
matrix:
    include:
        - os: osx
          language: generic
          before_install:
              - brew update
              - brew install pandoc
              - brew cask install basictex
          install:
              - export PATH="/Library/TeX/texbin:$PATH" && sudo tlmgr update --self
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins xecjk
script:
    - make -j4
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "en.epub"
    - "en.pdf"
    - "zh.epub"
    - "zh.pdf"
  skip_cleanup: true
  on:
    tags: true
