branches:
  only:
  - master
  - /^v[0-9]/
matrix:
    include:
        # kaiti.ttc shipped with Mac
        - os: osx
          osx_image: xcode10
          language: generic
          before_install:
            - |
              brew upgrade python || :
          install:
              - pip3 install -U pip future pantable
              - brew update
              - brew install pandoc opencc
              - brew cask install basictex
              - export PATH="/Library/TeX/texbin:$PATH" && sudo tlmgr update --self
              - sudo tlmgr install fourier ifetex latexmk lm-math placeins utopia
              # debug
              - cat /usr/local/texlive/2018basic/texmf-var/web2c/tlmgr.log
          cache:
          - pip
script:
    - fc-list : family # see available fonts
    - make -j3
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "en.epub"
    - "en.pdf"
    - "zh-Hant.epub"
    - "zh-Hant.pdf"
    - "zh-Hans.epub"
    - "zh-Hans.pdf"
    - "en-zh-Hant.epub"
    - "en-zh-Hant.pdf"
    - "en-zh-Hans.epub"
    - "en-zh-Hans.pdf"
  skip_cleanup: true
  on:
    tags: true
