branches:
  only:
  - master
  - /^v[0-9]/
matrix:
    include:
        # kaiti.ttc shipped with Mac
        - os: osx
          language: generic
          before_install:
              - brew update
              - brew install pandoc opencc python3
              - brew cask install basictex
              - pip3 install -U pip
              - pip3 install -U future
              - pip3 install -U pantable
          install:
              - export PATH="/Library/TeX/texbin:$PATH" && sudo tlmgr update --self
              - sudo tlmgr install latexmk fourier utopia placeins xecjk
          cache:
          - pip
script:
    - make -j4
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "en.epub"
    - "en.pdf"
    - "zh-Hant.epub"
    - "zh-Hant.pdf"
    - "zh-Hans.epub"
    - "zh-Hans.pdf"
    - "en-zh-Hant.epub"
    - "en-zh-Hant.pdf"
    - "en-zh-Hans.epub"
    - "en-zh-Hans.pdf"
  skip_cleanup: true
  on:
    tags: true
