branches:
  only:
  - master
  - /^v[0-9]/
matrix:
    include:
        - os: osx
          language: generic
          before_install:
              - brew update
              - brew install pandoc opencc
              - brew cask install basictex
              - pip install -U pip pantable
          install:
              - export PATH="/Library/TeX/texbin:$PATH" && sudo tlmgr update --self
              - sudo tlmgr install latexmk physics cancel fourier utopia siunitx placeins xecjk
          cache:
            pip: true
            directories:
            - $TRAVIS_BUILD_DIR
script:
    - make -j4
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - "en.epub"
    - "en.pdf"
    - "zh-Hant.epub"
    - "zh-Hant.pdf"
    - "zh-Hans.epub"
    - "zh-Hans.pdf"
    - "en-zh-Hant.epub"
    - "en-zh-Hant.pdf"
    - "en-zh-Hans.epub"
    - "en-zh-Hans.pdf"
  skip_cleanup: true
  on:
    tags: true
